src/App.js, src/components/AudioRecorderTamil/AudioRecorderTamil.js, src/components/VoiceCompair/VoiceCompair.js, src/views/Speak/Speak.js, src/views/StartLearn/StartLearn.js, src/viewsProto2/Speak/Speak.js, src/viewsProto3/Speak/Speak.js, src/viewsProto3/StartLearn/StartLearn.js, src/viewsProto4/Speak/Speak.js, src/viewsProto4/StartLearn/StartLearn.js
=> Issue #5 feat: Capture Sentence results [Telemetry Enhancements]

src/components/AudioRecorderTamil/AudioRecorderTamil.js, src/components/VoiceCompair/VoiceCompair.js, src/services/telementryService.js
User friendly Msg based API call duration (to manage user experience)
=> User friendly Msg based API call duration (Show alert if api response is taking time)

src/App.js, src/services/telementryService.js
Fail safty added to localstorage token key
=> Fail safty added to localstorage token key

public/index.html
=> uncomment_old_jquery

src/components2/NewTopHomeNextBar/NewTopHomeNextBar.js, src/viewsProto3/Score/Score.js, src/viewsProto3/StartLearn/StartLearn.js
=> work_done_on_paragraph_hide

src/index.css, src/viewsProto3/StartLearn/StartLearn.js
1. Swap Eng With Tamil Word and Sentence in Explore and Learn Section of Mozhigal WebApp
=> swap the telugu and english word and sentence in Explore and Learn

src/index.css, src/viewsProto3/Score/Score.js, src/viewsProto3/StartLearn/StartLearn.js
just reduce the size of tamil text
=> Myownchanges ajinkya

src/viewsProto2/Start/Start.js, src/viewsProto3/Start/Start3.js, src/viewsProto4/Start/Start.js
=> Task #200152 chore: updated code for alt tag on different prototypes

src/components/AudioRecorderTamil/AudioRecorderTamil.js, src/components/VoiceCompair/VoiceCompair.js
Hi Gourav,
**For Tamil:**
**For English:**
Thanks,
Vaibhav
=> Updated ASR API4Bharat host & endpoint for english & tamil language

src/views/Score/Score.js, src/viewsProto2/Score/Score.js, src/viewsProto3/Score/Score.js, src/viewsProto4/Score/Score.js
Worked on Sentence Sequence of Score.
=> Sentence Sequence and Score of Result

src/component/layout/Layout.js, src/components/VoiceCompair/VoiceCompair.js, src/pages/Contents.js, src/services/contentServices.js, src/utils/Const/ContentJSON.js, src/viewsProto3/Start/Start3.js, src/viewsProto3/StartLearn/StartLearn.js, src/viewsProto4/Start/Start.js, src/viewsProto4/StartLearn/StartLearn.js
Hi Sudeep/Gourav,
Thanks,
Vaibhav
=> Teacher workflow - for Author Sentence and Words [Contents]

src/components/VoiceCompair/VoiceCompair.js
Hi Gourav,
Please remove & merge this PR.
Thanks,
Vaibhav
=> ASR API - Added the missing code about AbortError

src/components/VoiceCompair/VoiceCompair.js
Hi Gourav,
Please remove & merge this PR.
Thanks,
Vaibhav
=> Hot Fix about missed code related abort controller

package.json, src/pages/Contents.js, src/services/contentServices.js
=> Updated Changes - Teacher workflow - for Author Sentence and Words [Contents] 

src/components/AudioRecorderTamil/AudioRecorderTamil.js, src/components/VoiceCompair/VoiceCompair.js, src/pages/ExploreAndLearn/Score/Score.js, src/pages/ExploreAndLearn/StartLearn/StartLearn.js, src/pages/PlayAndLearn/Score.js, src/pages/PlayAndLearn/StartLearn.js, src/services/callTelemetryIntract.js, src/services/telementryService.js
Added telemetry configuration in ALL
=> Added telemetry configuration in ALL

src/App.js, src/index.js, src/pages/ExploreAndLearn/Score/Score.js, src/pages/ExploreAndLearn/StartLearn/StartLearn.js, src/pages/PlayAndLearn/Score.js, src/pages/PlayAndLearn/StartLearn.js, src/services/callTelemetryIntract.js, src/services/telementryService.js
[ALL] React APP Telemetry not working for root url
=> Bug #204894 [ALL] React APP Telemetry not working for root url for 

src/components/AudioRecorderCompairUI/AudioRecorderCompairUI.js, src/components/AudioRecorderTamil/AudioRecorderTamil.js
[Uploading mic on off issue.webm…]()
=> Bug #206320 Issue of Handling Mic-Off Audio Capture of User

public/index.html, public/web-bad/audioStream.js, public/web-bad/volume-meter.js, src/components/AudioRecorderCompairUI/AudioRecorderCompairUI.js, src/components/VoiceCompair/VoiceCompair.js
Issue #207378 fix: audio preprocessing for en language
=> Issue #207378 fix: audio preproccesing for en language

src/pages/Story/Story.css, src/pages/Test-Rig-Two/Story/Story.jsx
Issue #208906 fix: css issue fixed for practice page
=> Issue #208906 fix: css issue fixed for practice page

src/pages/Test-Rig-Two/Story/Story.jsx
Issue #208906 fix: css issue fixed
=> Issue #208906 fix: css issue fixed

src/pages/Test-Rig-Two/Story/Story.jsx
Issue #209962 feat: Show random words and sentences from the content service
=> Issue #209962 feat: Show random words and sentences from content service

src/pages/Test-Rig-Two/Result/Result.css, src/pages/Test-Rig-Two/Result/Validate.jsx
Issue #209734 fix: validate page updates for version 2 APIs
=> Issue #209734 fix: validate page updates for version 2 APIs

src/pages/Test-Rig-Two/Result/Validate.jsx
Issue #209734 fix: Loading screen issue fixed
=> Issue #209734 fix: Loading screen issue fixed

src/pages/Story/StoryList.js
Issue #209734 fix: Storylist css issue fixes
=> Issue #209734 fix: Storylist css issue fixes

src/components/AudioRecorderCompairUI/AudioRecorderCompairUI.js, src/pages/Results.js, src/pages/Story/Story.jsx
Issue #209734 fix: Audio issue fixes for tamil story
=> Issue #209734 fix: Audio issue fixes for tamil story

src/pages/Story/Story.css, src/pages/Story/Story.jsx
Issue #209734 fix: Story page css issue fixes
=> Issue #209734 fix: Story page css issue fixes

src/components/AppDrawer/AppDrawer.js, src/pages/Test-Rig-Two/Story/Story.jsx
Issue #211198 feat: timer for logged in session
=> Issue #211198 feat: timer for logged in session

src/App.js, src/pages/Login.js
Issue #0000 fix: login issue fixes for login route
=> Issue #0000 fix: login issue fixes for login route

src/components/AppTimer/AppTimer.jsx
Issue #0000 fix: prod version updates
=> Issue #0000 fix: prod version updates

src/pages/Login.js, src/pages/Test-Rig-Two/Story/Story.jsx
Issue #0000 fix: user state issue fixes
=> Issue #0000 fix: user state issue fixes

src/components/AppDrawer/AppDrawer.js, src/pages/Story/Showcase.jsx, src/pages/Test-Rig-Two/Story/Story.jsx
Issue #211646 fix: Get milestone API changes
=> Issue #211646 fix: Get milestone API changes

src/App.js, src/config/practiceConfig.js
[Issue #210730 fix: Timer and points issue fixes](https://github.com/Sunbird-ALL/all-ll-app/commit/3a8ebf36fc140406a67655581bdb2048116f63c6)
=> Issue #210730 fix: Timer and points issue fixes

src/pages/Test-Rig-Two/Story/Story.jsx
Issue #210730 fix: Duplication of the sentences issue fixed
=> Issue #210730 fix: Duplication of the sentences issue fixed

src/pages/Test-Rig-Two/Story/Story.jsx
Issue #0000: Fixed duplicate if-else issue
=> Issue #0000: Fixed duplicate if-else issue

src/App.js, src/components/AppDrawer/AppDrawer.js, src/pages/Login.js, src/pages/Results.js, src/pages/Story/Discover.jsx, src/pages/Story/DiscoveryList.js, src/pages/Story/Showcase.jsx, src/pages/Story/Story.jsx, src/pages/Test-Rig-Two/Result/Validate.jsx, src/pages/Test-Rig-Two/Story/Story.jsx, src/services/telementryService.js, src/utils/api/PointerApi.js
Issue #211864: Env variables changes for react build
=> Issue #211864: Env variables changes for react build

src/index.js
Issue #211864 fix: Increase the duration by 1 sec
=> Issue #211864 fix: Increase the duration by 1 sec

src/pages/Story/Discover.jsx, src/pages/Story/DiscoveryList.js
Issue #0000 fix: Exit criteria update
=> Issue #0000 fix: Exit criteria update

src/pages/Story/Discover.jsx
Issue #0000 feat: failed user if pass - exit the discovery
=> Issue #0000 feat: failed user if pass - exit the discovery

src/pages/Test-Rig-Two/Story/Story.jsx
Issue #213397 feat: Assemble the word
=> Issue #213397 feat: Assemble the word

src/App.js, src/pages/Results.js, src/pages/Story/Discover.jsx, src/pages/Story/Showcase.jsx, src/pages/Test-Rig-Two/Story/SpellAndCheck.css, src/pages/Test-Rig-Two/Story/SpellAndCheck.jsx, src/pages/Test-Rig-Two/Story/Story.jsx
=> Kannda support

src/pages/Test-Rig-Two/Story/SpellAndCheck.jsx, src/pages/Test-Rig-Two/Story/Story.jsx
=> Issue #0000: next line issue

src/pages/Test-Rig-Two/Story/SpellAndCheck.jsx
Issue #0000: duplicate char issue
=> Issue #0000: duplicate char issue

src/index.css, src/pages/Test-Rig-Two/Story/Story.jsx
Issue #0000 fix: pointer for highlighted word
=> Issue #0000 fix: pointer for highlighted word

.github/workflows/aws.yml
Issue #0000 fix: workflow name changes
=> Issue #0000 fix: workflow name changes

src/pages/Test-Rig-Two/Story/Story.jsx
- Removed split function and used Splitgrapheme.
- Removed a console statement
=> Task #0000 fix: Changed Split function to Splitgraphene package in Highlighting words.
